/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_audio_AudioCore_AudioCallback */

#ifndef _Included_com_aispeech_audio_AudioCore_AudioCallback
#define _Included_com_aispeech_audio_AudioCore_AudioCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
