/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_ffmpeg_lib_FfmpegUtil */

#ifndef _Included_com_aispeech_ffmpeg_lib_FfmpegUtil
#define _Included_com_aispeech_ffmpeg_lib_FfmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_ffmpeg_lib_FfmpegUtil
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aispeech_ffmpeg_1lib_FfmpegUtil_stringFromJNI
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
