/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_audio_AudioCore */

#ifndef _Included_com_aispeech_audio_AudioCore
#define _Included_com_aispeech_audio_AudioCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_audio_AudioCore
 * Method:    start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aispeech_audio_AudioCore_parpare
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_aispeech_audio_AudioCore_start
        (JNIEnv *, jobject);
/*
 * Class:     com_aispeech_audio_AudioCore
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aispeech_audio_AudioCore_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
